name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs: 
      name: 
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_clippy_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.3
        with:
          release: '9-2019-q4'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clang
        run: sudo apt-get update && sudo apt install -y clang
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt, clippy
      - name: Install cargo-ledger
        run: cargo install --git=https://github.com/LedgerHQ/cargo-ledger
      - name: Setup cargo-ledger
        run: cargo ledger setup
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Build app
        run: cargo ledger build nanosplus

